# Generated by Django 5.1.5 on 2025-12-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duenios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenio',
            name='dni',
            field=models.CharField(default=45656454, max_length=15),
            preserve_default=False,
        ),
    ]
