# Generated by Django 6.0.1 on 2026-01-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duenios', '0003_alter_duenio_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenio',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
