# Generated by Django 5.1.5 on 2025-12-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duenios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duenios.duenio')),
            ],
        ),
    ]
