# Generated by Django 5.1.5 on 2025-12-29 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='veterinario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veterinarios.veterinario'),
            preserve_default=False,
        ),
    ]
