# Generated by Django 5.1.5 on 2025-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('TRATAMIENTO', 'En Tratamiento'), ('VACUNACION', 'Vacunación Pendiente')], max_length=100),
        ),
    ]
