# Generated by Django 5.1.5 on 2025-12-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_alter_estado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='veterinario',
        ),
    ]
