# Generated by Django 5.1.5 on 2026-01-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_remove_animal_veterinario'),
        ('duenios', '0002_duenio_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='duenios.duenio'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('TRATAMIENTO', 'En Tratamiento'), ('VACUNACION', 'Vacunación Pendiente'), ('INTERNACION', 'Internacion'), ('DESPARASITACION', 'Desparasitacion')], max_length=100),
        ),
    ]
