# Generated by Django 5.1.5 on 2026-01-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_alter_animal_duenio_alter_estado_estado'),
        ('duenios', '0002_duenio_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(blank=True, choices=[('TRATAMIENTO', 'En Tratamiento'), ('VACUNACION', 'Vacunación Pendiente'), ('INTERNACION', 'Internacion'), ('DESPARASITACION', 'Desparasitacion')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='duenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='duenios.duenio'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
