# Generated by Django 5.1.5 on 2026-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_animal_estado_alter_animal_duenio_alter_animal_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('TRATAMIENTO', 'En Tratamiento'), ('VACUNACION', 'Vacunación Pendiente'), ('INTERNACION', 'Internacion'), ('DESPARASITACION', 'Desparasitacion')], default='TRATAMIENTO', max_length=100),
        ),
    ]
