# Generated by Django 5.1.5 on 2026-01-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0008_alter_animal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('TRATAMIENTO', 'En Tratamiento'), ('VACUNACION', 'Vacunación Pendiente'), ('INTERNACION', 'Internacion'), ('DESPARASITACION', 'Desparasitacion'), ('SANO', 'Sano'), ('FALLECIDO', 'Fallecido')], default='TRATAMIENTO', max_length=100),
        ),
    ]
