# Generated by Django 5.1.5 on 2026-01-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0009_alter_animal_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RX', 'Radiografía'), ('SANGRE', 'Análisis de Sangre'), ('ECO', 'Ecografía'), ('OTRO', 'Otro')], max_length=100)),
                ('informe', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios/%Y/%m/%d/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='animales.animal')),
            ],
        ),
    ]
