# Generated by Django 6.0.1 on 2026-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0010_estudios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudios',
            options={'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
        migrations.AddField(
            model_name='estudios',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='tipo',
            field=models.CharField(choices=[('RX', 'Radiografía'), ('SANGRE', 'Análisis de Sangre'), ('ECO', 'Ecografía'), ('ORINA', 'Análisis de Orina'), ('OTRO', 'Otro')], max_length=100),
        ),
    ]
