# Generated by Django 6.0.1 on 2026-02-02 20:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0011_alter_estudios_options_estudios_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='archivo',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='archivo'),
            preserve_default=False,
        ),
    ]
