# Generated by Django 6.0.1 on 2026-02-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0012_alter_estudios_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='archivo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
