# Generated by Django 5.1.5 on 2025-12-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
        ('veterinarios', '0002_horario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('veterinario', 'fecha', 'hora')},
        ),
    ]
