# Generated by Django 5.1.5 on 2026-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='motivo',
            field=models.CharField(default='Consulta', max_length=100),
            preserve_default=False,
        ),
    ]
