# Generated by Django 5.1.5 on 2026-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_turno_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Reprogramado', 'Reprogramado'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
    ]
