# Generated by Django 5.1.5 on 2026-01-15 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_alter_animal_duenio_alter_estado_estado'),
        ('turnos', '0004_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animales.animal'),
        ),
    ]
