# Generated by Django 5.1.5 on 2026-01-17 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0009_alter_animal_estado'),
        ('veterinarios', '0002_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jaulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.animal')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarios.veterinario')),
                ('jaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internacion.jaulas')),
            ],
        ),
    ]
