# Generated by Django 5.1.5 on 2026-01-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internacion',
            options={'verbose_name': 'Internacion', 'verbose_name_plural': 'Internaciones'},
        ),
        migrations.AlterModelOptions(
            name='jaulas',
            options={'verbose_name': 'Jaula', 'verbose_name_plural': 'Jaulas'},
        ),
    ]
