# Generated by Django 5.1.5 on 2026-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0002_alter_internacion_options_alter_jaulas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacion',
            name='nivel_urgencia',
            field=models.CharField(blank=True, choices=[('EMERGENCIA', 'Emergencia'), ('OBSERVACION', 'Observacion'), ('CONTROL', 'Control')], max_length=100, null=True),
        ),
    ]
