# Generated by Django 5.1.5 on 2026-01-19 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0003_internacion_nivel_urgencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_observaciones', to='internacion.internacion')),
            ],
        ),
    ]
