# Generated by Django 5.1.5 on 2026-01-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0004_observaciones'),
        ('veterinarios', '0002_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='veterinario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='veterinarios.veterinario'),
            preserve_default=False,
        ),
    ]
